package all.dao;

import all.bean.Deportment;
import all.bean.DeportmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeportmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    long countByExample(DeportmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int deleteByExample(DeportmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int insert(Deportment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int insertSelective(Deportment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    List<Deportment> selectByExample(DeportmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    Deportment selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") Deportment record, @Param("example") DeportmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int updateByExample(@Param("record") Deportment record, @Param("example") DeportmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int updateByPrimaryKeySelective(Deportment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Feb 22 11:08:08 CST 2021
     */
    int updateByPrimaryKey(Deportment record);
}